config/routes.rb
Rails.application.routes.draw do
  resources :attendants
  get 'users/index'
  match '/users',   to: 'users#index',   via: 'get'
  devise_for :users
  resources :groups
  root to: 'groups#index'

end

app/models/attendant.rb
class Attendant < ActiveRecord::Base
	has_and_belongs_to_many :groups
end

app/models/group.rb
class Group < ActiveRecord::Base
	has_and_belongs_to_many :attendants
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_and_belongs_to_many :groups
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/attendants_controller.rb
class AttendantsController < ApplicationController
  before_action :set_attendant, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /attendants
  # GET /attendants.json
  def index
    if params[:radio_type] == "name" && params[:filter_value] != ""
      @attendants = Attendant.where({ first_name: params[:filter_value]})
    elsif params[:radio_type] == "id" && params[:filter_value] != ""
      @attendants = Attendant.where({ attendant_type_id: params[:filter_value]})
    else
      @attendants = Attendant.all
    end
    logger.debug 'test'
  end

  # GET /attendants/1
  # GET /attendants/1.json
  def show
  end

  # GET /attendants/new
  def new
    @attendant = Attendant.new
  end

  # GET /attendants/1/edit
  def edit
  end

  # POST /attendants
  # POST /attendants.json
  def create
    @attendant = Attendant.new(attendant_params)

    respond_to do |format|
      if @attendant.save
        format.html { redirect_to @attendant, notice: 'Attendant was successfully created.' }
        format.json { render :show, status: :created, location: @attendant }
      else
        format.html { render :new }
        format.json { render json: @attendant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attendants/1
  # PATCH/PUT /attendants/1.json
  def update
    respond_to do |format|
      if @attendant.update(attendant_params)
        format.html { redirect_to @attendant, notice: 'Attendant was successfully updated.' }
        format.json { render :show, status: :ok, location: @attendant }
      else
        format.html { render :edit }
        format.json { render json: @attendant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendants/1
  # DELETE /attendants/1.json
  def destroy
    @attendant.destroy
    respond_to do |format|
      format.html { redirect_to attendants_url, notice: 'Attendant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attendant
      @attendant = Attendant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attendant_params
      params.require(:attendant).permit(:first_name, :last_name, :citizen_id, :login, :password, :attendant_type, :attendant_type_id, :dept_name)
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /groups
  # GET /groups.json
  def index
    if params[:radio_type] == "name" && params[:filter_value] != ""
      @groups = Group.where({ group_name: params[:filter_value]})
    elsif params[:radio_type] == "greater" && params[:filter_value] != ""
      @groups = Group.where({ score: params[:filter_value].to_i..Float::INFINITY})
    elsif params[:radio_type] == "lesser" && params[:filter_value] != ""
      @groups = Group.where({ score: -Float::INFINITY..params[:filter_value].to_i})
    else
      @groups = Group.all
    end
    logger.debug params[:filter_value].to_i
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    @attendants = Attendant.find(params[:attendants_id])
    @group.attendants = @attendants

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    @attendants = Attendant.find(params[:attendants_id])
    @group.attendants = @attendants
    
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:group_name, :score)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendants_helper.rb
module AttendantsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attendants/_form.html.erb
<%= form_for(@attendant) do |f| %>
  <% if @attendant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attendant.errors.count, "error") %> prohibited this attendant from being saved:</h2>

      <ul>
      <% @attendant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :citizen_id %><br>
    <%= f.text_field :citizen_id %>
  </div>
  <div class="field">
    <%= f.label :login %><br>
    <%= f.text_field :login %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :attendant_type %><br>
    <%= f.text_field :attendant_type %>
  </div>
  <div class="field">
    <%= f.label :attendant_type_id %><br>
    <%= f.text_field :attendant_type_id %>
  </div>
  <div class="field">
    <%= f.label :dept_name %><br>
    <%= f.text_field :dept_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attendants/edit.html.erb
<h1>Editing Attendant</h1>

<%= render 'form' %>

<%= link_to 'Show', @attendant %> |
<%= link_to 'Back', attendants_path %>

app/views/attendants/index.html.erb
<p id="notice"><%= notice %></p>

<%= form_tag '', :method => :get do %>
  <%= text_field_tag :filter_value %>
  <%= radio_button_tag(:radio_type, "name") %>
    <%= label_tag(:first_name, "First Name") %>
  <%= radio_button_tag(:radio_type, "id") %>
    <%= label_tag(:user_type_id, "Student ID") %>
  <%= submit_tag 'Filter' %>
<% end %>

<h5>For group filtering please go to GroupsList page</h5>

<h1>Listing Attendants</h1>

<table>
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Citizen ID</th>
      <th>Login</th>
      <th>Password</th>
      <th>Attendant Type</th>
      <th>Attendant Type ID</th>
      <th>Department Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attendants.each do |attendant| %>
      <tr>
        <td><%= attendant.first_name %></td>
        <td><%= attendant.last_name %></td>
        <td><%= attendant.citizen_id %></td>
        <td><%= attendant.login %></td>
        <td><%= attendant.password %></td>
        <td><%= attendant.attendant_type %></td>
        <td><%= attendant.attendant_type_id %></td>
        <td><%= attendant.dept_name %></td>
        <td><%= link_to 'Show', attendant %></td>
        <td><%= link_to 'Edit', edit_attendant_path(attendant) %></td>
        <td><%= link_to 'Destroy', attendant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attendant', new_attendant_path %>
<%= link_to 'Users List', users_path %>
<%= link_to 'Groups List', groups_path %>

app/views/attendants/new.html.erb
<h1>New Attendant</h1>
<h4>(Please fill all fields except User Type ID and Department Name)</h4>
<%= render 'form' %>

<%= link_to 'Back', attendants_path %>

app/views/attendants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First Name:</strong>
  <%= @attendant.first_name %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @attendant.last_name %>
</p>

<p>
  <strong>Citizen ID:</strong>
  <%= @attendant.citizen_id %>
</p>

<p>
  <strong>Login:</strong>
  <%= @attendant.login %>
</p>

<p>
  <strong>Password:</strong>
  <%= @attendant.password %>
</p>

<p>
  <strong>Attendant Type:</strong>
  <%= @attendant.attendant_type %>
</p>

<p>
  <strong>Attendant Type ID:</strong>
  <%= @attendant.attendant_type_id %>
</p>

<p>
  <strong>Department Name:</strong>
  <%= @attendant.dept_name %>
</p>

<%= link_to 'Edit', edit_attendant_path(@attendant) %> |
<%= link_to 'Back', attendants_path %>

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :group_name %><br>
    <%= f.text_field :group_name %>
  </div>
  <div class="field">
    <%= f.label :score %><br>
    <%= f.number_field :score %>
  </div>
  <% Attendant.all.each do |attendant| %>
      <li>
        <% if @group.attendants.exists?(attendant) %>
          <%= check_box_tag 'attendants_id[]', attendant.id, true %>
        <% else %>
          <%= check_box_tag 'attendants_id[]', attendant.id %>
        <% end %>
        <%= attendant.first_name -%>
      </li>
  <% end %><br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<%= form_tag '', :method => :get do %>
  <%= text_field_tag :filter_value %>
  <%= radio_button_tag(:radio_type, "name") %>
    <%= label_tag(:name, "Group Name") %>
  <%= radio_button_tag(:radio_type, "greater") %>
    <%= label_tag(:score, "Group Score >= n") %>
  <%= radio_button_tag(:radio_type, "lesser") %>
    <%= label_tag(:score, "Group Score <= n") %>
  <%= submit_tag 'Filter' %>
<% end %>

<h1>Listing Groups</h1>

<table>
  <thead>
    <tr>
      <th>Group Name&nbsp;&nbsp;&nbsp;&nbsp;</th>
      <th>Number of students&nbsp;&nbsp;&nbsp;&nbsp;</th>
      <th>Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.group_name %></td>
        <td><%= group.attendants.count %></td>
        <td><%= group.score %></td>
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group', new_group_path %>
<%= link_to 'Users List', users_path %>
<%= link_to 'Attendants List', attendants_path %>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Group name:</strong>
  <%= @group.group_name %>
</p>

<p>
  <strong>Score:</strong>
  <%= @group.score %>
</p>

<h2>Group members</h2>
<% Attendant.all.each do |attendant| %>
		<% if @group.attendants.exists?(attendant) %>
      <li><%= link_to attendant.first_name, attendant -%></li>
    <% end %>
<% end %><br>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DeviseTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= link_to "Sign Up", new_user_registration_path %>
<%= link_to "Sign In", new_user_session_path %>
<%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>
<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<% @users = User.all %>
<% @users.each do |user| %>
  <%= user.email %><br/>
<% end %>

<br>

<%= link_to 'Groups List', groups_path %>
<%= link_to 'Attendants List', attendants_path %>